=begin
Crimson Falcon - Ruby Client SDK

Code auto-generated by OpenAPI Generator; DO NOT EDIT.

MIT License

Copyright (c) 2023 Crowdstrike

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
=end

require 'spec_helper'
require 'json'

# Unit tests for Falcon::ApiClients
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ApiClients' do
  before(:all) do
    # run before each test
    @api_instance = Falcon::ApiClients.new
  end

  after(:all) do
    # run after each test
  end

  describe 'test an instance of ApiClients' do
    it 'should create an instance of ApiClients' do
      expect(@api_instance).to be_instance_of(Falcon::ApiClients)
    end
  end

  # unit tests for create_api_client
  # Create new API Client.
  # @param body
  # @param [Hash] opts the optional parameters
  # @return [MsaEntitiesResponse]
  describe 'create_api_client test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_api_clients
  # Delete existing API Client(s) based on API Client ID(s) provided as request parameter(s) &#39;ids&#39;.
  # @param ids The API Client ID(s) for which API Client(s) have to be deleted.
  # @param [Hash] opts the optional parameters
  # @return [MsaEntitiesResponse]
  describe 'delete_api_clients test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_accessible_scopes
  # Get all available scopes for customer.
  # @param [Hash] opts the optional parameters
  # @return [ApiAccessibleScopesResponse]
  describe 'get_accessible_scopes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_all_api_client_ids_for_customer
  # Get All API client ID(s) for customer.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset Starting index of overall result set from which to return ids.
  # @option opts [Integer] :limit Number of ids to return.
  # @option opts [String] :sort Possible values for sort by field includes id, name, created_by, updated_by, created_timestamp, last_modified. Ex: &#39;name|asc&#39;, &#39;name|desc&#39;, etc.
  # @return [MsaQueryResponse]
  describe 'get_all_api_client_ids_for_customer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_api_clients
  # Get API Client(s) based on API Client ID(s) provided as request parameter(s) &#39;ids&#39;.
  # @param ids The API Client ID(s) for which to obtain API Client definition(s).
  # @param [Hash] opts the optional parameters
  # @return [MsaEntitiesResponse]
  describe 'get_api_clients test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reset_api_client_secret
  # Reset existing API Client(s)&#39;s secret based on API Client ID(s) provided as request parameter(s) &#39;ids&#39;. API Client Secret can be reset by specifying appropriate action in request parameter &#39;action_name&#39;.
  # @param ids The API Client ID(s) for which to perform action on API Client(s).
  # @param action_name Action to perform as part of API Client update. Only allowed value is &#39;reset_secret&#39;.
  # @param [Hash] opts the optional parameters
  # @return [MsaEntitiesResponse]
  describe 'reset_api_client_secret test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_api_client
  # Update existing API Client based on API Client ID provided as request parameter &#39;ids&#39;. Client Secret remains unaffected.
  # @param ids The API Client ID for which to update the API Client definition.
  # @param body
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'update_api_client test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
