=begin
Crimson Falcon - Ruby Client SDK

Code auto-generated by OpenAPI Generator; DO NOT EDIT.

MIT License

Copyright (c) 2023 Crowdstrike

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
=end

require 'spec_helper'
require 'json'

# Unit tests for Falcon::CloudAzureRegistration
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CloudAzureRegistration' do
  before(:all) do
    # run before each test
    @api_instance = Falcon::CloudAzureRegistration.new
  end

  after(:all) do
    # run after each test
  end

  describe 'test an instance of CloudAzureRegistration' do
    it 'should create an instance of CloudAzureRegistration' do
      expect(@api_instance).to be_instance_of(Falcon::CloudAzureRegistration)
    end
  end

  # unit tests for cloud_registration_azure_create_registration
  # Create an Azure registration for a tenant.
  # @param body
  # @param [Hash] opts the optional parameters
  # @return [AzureAzureRegistrationResponseExtV1]
  describe 'cloud_registration_azure_create_registration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_registration_azure_create_suppressions
  # Create new issue suppression rules
  # @param body
  # @param [Hash] opts the optional parameters
  # @return [AzureSuppressionResponseExtV1]
  describe 'cloud_registration_azure_create_suppressions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_registration_azure_delete_legacy_subscription
  # Delete existing legacy Azure subscriptions.
  # @param body
  # @param [Hash] opts the optional parameters
  # @return [AzureLegacySubscriptionDeleteResponseExtV1]
  describe 'cloud_registration_azure_delete_legacy_subscription test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_registration_azure_delete_registration
  # Deletes existing Azure registrations.
  # @param tenant_ids Azure tenant IDs
  # @param [Hash] opts the optional parameters
  # @return [AzureDeleteRegistrationResponseExtV1]
  describe 'cloud_registration_azure_delete_registration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_registration_azure_delete_suppressions
  # Remove/revoke suppression rules
  # @param body
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'cloud_registration_azure_delete_suppressions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_registration_azure_download_script
  # Retrieve script to create resources
  # @param body
  # @param [Hash] opts the optional parameters
  # @return [AzureAzureProvisionGetAccountScriptResponseV1]
  describe 'cloud_registration_azure_download_script test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_registration_azure_get_issue_suppression_values_by_field
  # Retrieve distinct filterable values for issue suppression fields
  # @param registration_id Registration ID to filter values by
  # @param field Field to get values for
  # @param [Hash] opts the optional parameters
  # @return [AzureIssueSuppressionValuesByFieldResponse]
  describe 'cloud_registration_azure_get_issue_suppression_values_by_field test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_registration_azure_get_issue_values_by_field
  # Retrieve distinct filterable values for issue fields
  # @param registration_id Registration ID to filter values by
  # @param field Field to get values for
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter FQL (Falcon Query Language) string for filtering results. Allowed filters are name,issue,severity,category,impact,entity_type,entity_id,entity_name,status
  # @return [AzureIssueValuesByFieldResponse]
  describe 'cloud_registration_azure_get_issue_values_by_field test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_registration_azure_get_issues
  # Retrieve issues for Azure registrations
  # @param registration_id Registration ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter FQL (Falcon Query Language) string for filtering results. Allowed filters are name,issue,severity,category,impact,entity_type,entity_id,entity_name,status
  # @option opts [String] :sort Field and direction for sorting results - allowed sort fields are issue,name,severity,category,impact,entity_type,entity_id,entity_name,impacted_entities
  # @option opts [String] :group_by Grouping method: &#39;name&#39; (optional, default: ungrouped)
  # @option opts [Integer] :limit Maximum number of records to return (default: 100, max: 1000)
  # @option opts [Integer] :offset Starting index of result
  # @return [AzureIssueResponseExtV1]
  describe 'cloud_registration_azure_get_issues test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_registration_azure_get_registration
  # Retrieve existing Azure registration for a tenant.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :tenant_id Tenant ID
  # @option opts [String] :registration_id Registration ID
  # @return [AzureAzureRegistrationResponseExtV1]
  describe 'cloud_registration_azure_get_registration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_registration_azure_get_script
  # Download Azure deployment script (Terraform or Bicep)
  # @param tenant_id Azure tenant ID
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'cloud_registration_azure_get_script test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_registration_azure_get_script_versions
  # Retrieve all available script versions with filtering and sorting
  # @param deployment_method Filter by deployment method (e.g., &#39;bicep-legacy&#39;, &#39;bicep-deployment-stack&#39;)
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort Field and direction for sorting results - allowed sort fields are version,deployment_method,published_date
  # @option opts [Integer] :limit Maximum number of records to return (default: 100, max: 1000)
  # @option opts [Integer] :offset Starting index of result
  # @return [AzureScriptVersionResponseExtV1]
  describe 'cloud_registration_azure_get_script_versions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_registration_azure_get_suppressions
  # Retrieve existing suppression rules with filtering
  # @param registration_id Registration ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter FQL (Falcon Query Language) string for filtering results. Allowed filters are issue_name,entity_id,suppressed_by,created_at,reason
  # @option opts [String] :sort Field and direction for sorting results - allowed sort fields are issue_name,entity_id,suppressed_by,created_at,reason
  # @option opts [Integer] :limit Maximum number of records to return (default: 100, max: 1000)
  # @option opts [Integer] :offset Starting index of result
  # @return [AzureSuppressionResponseExtV1]
  describe 'cloud_registration_azure_get_suppressions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_registration_azure_trigger_health_check
  # Trigger health check scan for Azure registrations
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tenant_ids Azure tenant IDs
  # @return [AzureHealthCheckTriggerResponseExtV1]
  describe 'cloud_registration_azure_trigger_health_check test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_registration_azure_update_registration
  # Update an existing Azure registration for a tenant.
  # @param body
  # @param [Hash] opts the optional parameters
  # @return [AzureAzureRegistrationResponseExtV1]
  describe 'cloud_registration_azure_update_registration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_registration_azure_update_suppressions
  # Update existing suppression rules
  # @param body
  # @param [Hash] opts the optional parameters
  # @return [AzureSuppressionResponseExtV1]
  describe 'cloud_registration_azure_update_suppressions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cloud_registration_azure_validate_registration
  # Validate an Azure registration by checking service principal, role assignments and deployment stack (if the deployment method is Bicep)
  # @param tenant_id Azure tenant ID to be validated
  # @param [Hash] opts the optional parameters
  # @option opts [String] :stack_name Azure deployment stack name to be validated
  # @return [AzureRegistrationValidateResponseV1]
  describe 'cloud_registration_azure_validate_registration test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
