=begin
Crimson Falcon - Ruby Client SDK

Code auto-generated by OpenAPI Generator; DO NOT EDIT.

MIT License

Copyright (c) 2023 Crowdstrike

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
=end

require 'spec_helper'
require 'json'

# Unit tests for Falcon::FalconId
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FalconId' do
  before(:all) do
    # run before each test
    @api_instance = Falcon::FalconId.new
  end

  after(:all) do
    # run after each test
  end

  describe 'test an instance of FalconId' do
    it 'should create an instance of FalconId' do
      expect(@api_instance).to be_instance_of(Falcon::FalconId)
    end
  end

  # unit tests for delete_third_party_passkey_registry
  # Deletes third party passkey registries
  # @param ids Third party passkey registry IDs to delete
  # @param [Hash] opts the optional parameters
  # @return [FalconidapiThirdPartyPasskeyRegistryDeleteResponseV1]
  describe 'delete_third_party_passkey_registry test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_third_party_passkey_registry
  # Fetches third party passkey registries
  # @param ids Third party passkey registry IDs to retrieve
  # @param [Hash] opts the optional parameters
  # @return [FalconidapiThirdPartyPasskeyRegistryGetResponseV1]
  describe 'get_third_party_passkey_registry test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for query_third_party_passkey_registry
  # Query third party passkey registries
  # @param [Hash] opts the optional parameters
  # @option opts [String] :filter FQL filter
  # @option opts [Integer] :offset Paging offset
  # @option opts [Integer] :limit Paging limit
  # @option opts [String] :sort Sorting field and direction
  # @return [FalconidapiThirdPartyPasskeyRegistryQueryResponseV1]
  describe 'query_third_party_passkey_registry test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_third_party_passkey_registry
  # Updates third party passkey registries
  # @param body
  # @param [Hash] opts the optional parameters
  # @return [FalconidapiThirdPartyPasskeyRegistryPatchResponseV1]
  describe 'update_third_party_passkey_registry test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
