=begin
Crimson Falcon - Ruby Client SDK

Code auto-generated by OpenAPI Generator; DO NOT EDIT.

MIT License

Copyright (c) 2023 Crowdstrike

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
=end

require 'spec_helper'
require 'json'

# Unit tests for Falcon::ScanningOrchestrator
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ScanningOrchestrator' do
  before(:all) do
    # run before each test
    @api_instance = Falcon::ScanningOrchestrator.new
  end

  after(:all) do
    # run after each test
  end

  describe 'test an instance of ScanningOrchestrator' do
    it 'should create an instance of ScanningOrchestrator' do
      expect(@api_instance).to be_instance_of(Falcon::ScanningOrchestrator)
    end
  end

  # unit tests for create_schedules
  # Create scanning schedules
  # Create one or more scanning schedules
  # @param authorization Bearer Token
  # @param body Schedule resources to create
  # @param [Hash] opts the optional parameters
  # @return [TypesSchedulesResponse]
  describe 'create_schedules test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_schedules
  # Delete scanning schedules
  # Delete one or more scanning schedules by ID
  # @param authorization Bearer Token
  # @param ids Schedule IDs to delete
  # @param [Hash] opts the optional parameters
  # @return [MsaspecResponseFields]
  describe 'delete_schedules test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_combined_schedules
  # Get combined scanning schedules
  # Get schedules with pagination, sorting, and filtering
  # @param authorization Bearer Token
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Number of results to return
  # @option opts [Integer] :offset Starting offset for pagination
  # @option opts [String] :sort Sort field and direction. Available fields: scan_product, provider_type, enabled, name, created_at. Example: name|asc
  # @option opts [String] :filter FQL filter expression. Available fields: scan_product, provider_type, enabled, name, created_at. Example: enabled:true
  # @return [TypesSchedulesResponse]
  describe 'get_combined_schedules test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_schedules
  # Get scanning schedules
  # Get scanning schedules by their IDs
  # @param authorization Bearer Token
  # @param ids Schedule IDs to retrieve
  # @param [Hash] opts the optional parameters
  # @return [TypesSchedulesResponse]
  describe 'get_schedules test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_service_types
  # Get allowed service types
  # Returns the list of service types available for scanning
  # @param authorization Bearer Token
  # @param scan_product Scan product filter
  # @param [Hash] opts the optional parameters
  # @return [TypesServiceTypesResponse]
  describe 'get_service_types test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for search_schedules
  # Search scanning schedules
  # Search schedules and return IDs with pagination, sorting, and filtering
  # @param authorization Bearer Token
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit Number of results to return
  # @option opts [Integer] :offset Starting offset for pagination
  # @option opts [String] :sort Sort field and direction. Available fields: scan_product, provider_type, enabled, name, created_at. Example: name|asc
  # @option opts [String] :filter FQL filter expression. Available fields: scan_product, provider_type, enabled, name, created_at. Example: enabled:true
  # @return [Array<String>]
  describe 'search_schedules test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for trigger_scan_by_schedule
  # Trigger scan by schedule IDs
  # Triggers an immediate scan for the given schedule IDs
  # @param authorization Bearer Token
  # @param body Schedule IDs to trigger
  # @param [Hash] opts the optional parameters
  # @return [TypesSchedulesResponse]
  describe 'trigger_scan_by_schedule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_schedules
  # Update scanning schedules
  # Updates one or more scanning schedules
  # @param authorization Bearer Token
  # @param body Schedule resources to update (ID required in each resource)
  # @param [Hash] opts the optional parameters
  # @return [TypesSchedulesResponse]
  describe 'update_schedules test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
